### ISSUE TITLE
使用ApiRequest这个函数是为什么不能使用data装参数

### ISSUE THREAD

**Issue by abaozhizhong** [Werb/Pixel-Api#2]
const path = ApiConfig.API_ROUTER_CONFIG.userInfo +
        '?access_token=' + access_token +
        '&uid=' + uid +
        '&screen_name=' + screen_name 

ApiRequest(
        ApiConfig.HOST_CONCIG.host,
        path,
        'get',
        null,
        (response, code) => {
            res.status(code).send(response)
        },
        (err) => {
            res.status(500).send(err)
        }
    )
如上为什么不可以写成
ApiRequest(
        ApiConfig.HOST_CONCIG.host,
        path,
        'get',
        {
       access_token：xxxx,
      uid:xxx,
      screen_name:xxx
       },
        (response, code) => {
            res.status(code).send(response)
        },
        (err) => {
            res.status(500).send(err)
        }
    )
这种形式呢（踩了好久的坑，但是还是费解为啥不行）求回答呀大神

**Comment by werbhelius** [comment]
data 参数是 post 请求用的，get 请求直接拼在 url 后面就好了
